### ISSUE TITLE
Message center. The title above the message details is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#149]
全部消息列表点击进入消息详情，顶部应显示为“全部消息”
![image](https://user-images.githubusercontent.com/95004531/182549579-ca8053ba-0b89-4ffc-b7b6-c757369b7ac9.png)
![image](https://user-images.githubusercontent.com/95004531/182549605-c87d6693-caea-489f-9179-c50a1e0082e7.png)

**Comment by wzh425** [comment]
需求存疑

**Comment by LazyEar0** [comment]
resolved
