### ISSUE TITLE
Global navigation . Unable to switch to another system

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#189]
全局导航无法切换至其他项目
![image](https://user-images.githubusercontent.com/95004531/187354389-224dedb8-ba31-4c43-ae05-415ea92b7ebb.png)

**Comment by LazyEar0** [comment]
@codding-y  PM 的全局导航无法跳转到Auth

**Comment by MayueCif** [comment]
![image](https://user-images.githubusercontent.com/6133287/195801255-67c16594-b22f-4531-a197-edb1ad5041b8.png)

**Comment by LazyEar0** [comment]
resolved
