### ISSUE TITLE
If too much data is selected from the drop-down list, the spacing between the options needs to be adjusted

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#299]
下拉框中选择数据过多时，选项之间的间距需要调整
![image](https://user-images.githubusercontent.com/95004531/210920813-8ccf950c-985d-4e9b-9eea-512366aa7dea.png)

**Comment by zyz** [comment]
#367 SSlect component item style margin value is 4px override

**Comment by LazyEar0** [comment]
@zyz   参照PM设计稿调整间距
![image](https://user-images.githubusercontent.com/95004531/223638449-ed90863a-88cd-46b5-9be3-5359bfcf069a.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by zyz** [comment]
#410 SSlect style margin spacing is modified according to the design (16px 12px)
