### ISSUE TITLE
i18n After selecting the language, switch between projects, the language should be consistent

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#329]
i18n选择语言后，项目之间切换，语言应保持一致。现切换项目，语言不统一，如PM设置为英文，全局导航进入Auth后，语言仍是中文，需要再次设置语言。
![image](https://user-images.githubusercontent.com/95004531/217174541-c6141197-534e-4bd4-9662-93b0b380cd0a.png)

**Comment by MapleWithoutWords** [comment]
the question resolve solution:use second-level domain name sharing cookie.
![image](https://user-images.githubusercontent.com/38368335/224247173-7e76f4cc-6d07-4fca-9116-f19026bf552f.png)

**Comment by MapleWithoutWords** [comment]
first step:BlazorComponent add set cookie domain method:https://github.com/BlazorComponent/BlazorComponent/pull/338

**Comment by MapleWithoutWords** [comment]
wait pr merge,and publisher ```blazorComponent```.pr:https://github.com/BlazorComponent/BlazorComponent/pull/339

**Comment by MapleWithoutWords** [comment]
issues can only Test person close

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
已修复
