### ISSUE TITLE
Deletes popover style and text changes

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#336]
删除弹窗的样式及文本（中文+英文）修改，单词之间用空格间隔。请自查其他项目，类似问题一并修正。
实际结果：
![image](https://user-images.githubusercontent.com/95004531/218624704-cc3e75f7-b3f6-4346-b7ce-121092f2a2cc.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/218624947-e0c140b8-d06e-480a-9fd3-1228b9be20fd.png)

**Comment by MapleWithoutWords** [comment]
the question seem to already resolve.

**Comment by LazyEar0** [comment]
@MapleWithoutWords  删除弹窗及样式参照预期结果
实际结果：
![image](https://user-images.githubusercontent.com/95004531/223634996-5f516d32-9edf-43e5-b444-0418cfa7f580.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/223635032-3cf5dd7d-36be-4af3-9b3a-df3476eb6bc8.png)
