### ISSUE TITLE
In global navigation, the search menu in English is case insensitive

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#339]
全局导航，英文状态下，搜索菜单，应不区分大小写。
![image](https://user-images.githubusercontent.com/95004531/218653468-f0c57f83-818c-4b90-8be3-c71e68d7fc06.png)
![image](https://user-images.githubusercontent.com/95004531/218653494-6875c0c2-8fda-41c8-a70e-2258fd5fce43.png)
![image](https://user-images.githubusercontent.com/95004531/218653529-cf0d1302-317e-45d3-81cd-abc7065ac787.png)

**Comment by MapleWithoutWords** [comment]
the question seem to already resolve. this is effect image in english language under.
![image](https://user-images.githubusercontent.com/38368335/222611594-f1d4c9aa-ec10-44ad-a62d-5402fd96ec58.png)
