### ISSUE TITLE
Modify personal information, click to obtain verification code, error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#362]
修改个人信息，点击获取验证码，报错（获取短信验证码都存在此问题）
![image](https://user-images.githubusercontent.com/95004531/222666396-f2eea514-9508-447f-a2cc-47929e33875d.png)

**Comment by LazyEar0** [comment]
@MayueCif  此问题仍存在
![image](https://user-images.githubusercontent.com/95004531/223633822-350fc4a9-4daa-4ff6-a4ca-b9f9a5e600a3.png)

**Comment by LazyEar0** [comment]
测试环境此问题仍存在

**Comment by MayueCif** [comment]
报错地方加上InvokeAsync 代码

**Comment by zyz** [comment]
#422 add InvokeAsync
https://github.com/masastack/MASA.Auth/pull/844
Fix: SMS send issues
