### ISSUE TITLE
The demo environment gets SMS verification code error and does not disable SMS sending function

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#374]
演示环境获取短信验证码报错，且没有禁用发送短信功能
![image](https://user-images.githubusercontent.com/95004531/223053188-8dfffed1-a275-4df2-8ad0-7165eaeb903e.png)

**Comment by LazyEar0** [comment]
测试环境同样报错

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Auth/pull/844
Have been fixed

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Auth/pull/852
Fix:Demo environment forbid SMS send
