### ISSUE TITLE
The select gender button is misaligned

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#379]
英文状态下，修改个人信息，选择性别UI错位
![image](https://user-images.githubusercontent.com/95004531/223634350-7592ac4c-9d0e-462b-a964-a3c3cd16eb40.png)

**Comment by zyz** [comment]
#424 Fix: user-center i18n language toggle gender styles

**Comment by LazyEar0** [comment]
切换语言还是会错位
![image](https://user-images.githubusercontent.com/95004531/228798648-9e3fb1d9-7280-4a8c-a664-c3d3dad1648e.png)

**Comment by zyz** [comment]
#449 Fix: user-center i18n language toggle gender styles misaligned
