### ISSUE TITLE
Failed to obtain the SMS verification code

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#392]
获取短信验证码无效，没有在MC生成消息记录
![image](https://user-images.githubusercontent.com/95004531/224642847-9b1d8d9f-f67c-492f-941f-ab90a8091ea5.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Auth/pull/844
Fix: Changing personal information to the phonenumber, send SMS invalid
