### ISSUE TITLE
Moving the mouse over the page will penetrate the top navigation bar

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#412]
鼠标滑动页面，会穿透顶部导航栏
![image](https://user-images.githubusercontent.com/95004531/225845113-78bbde65-0cc3-41ed-91d1-badc125c8231.png)

**Comment by kogel-net** [comment]
#414

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/226525997-6c58e6bc-0136-41b4-a0a0-c933622b3673.png)

@xie1wei2 请确认此问题解决方案

**Comment by xie1wei2** [comment]
左侧导航栏为一个区域，底部导航为一个区域（且顶部是固定位置）剩余部分为内容区域，内容有滚动也是这个框里面进行滑动。跟上面透视那个没有关系。
![image](https://user-images.githubusercontent.com/101324746/226526702-ba206b30-ecb8-466d-b8ff-8104f4730dc0.png)

**Comment by LazyEar0** [comment]
AppBar 增加了背景色
