### ISSUE TITLE
Site message details with jump link missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#413]
带有跳转链接的站内信，在消息列表点击消息就直接跳转至URL的地址，应先进入消息详情页，在消息详情页点击跳转至指定链接。
@xie1wei2  这个页面缺失，需出设计稿后开发修改。
![image](https://user-images.githubusercontent.com/95004531/225861797-c02ddb13-a60f-4a96-8e3b-d2a80b1cbd15.png)

**Comment by wzh425** [comment]
目前是直接跳转链接

**Comment by limei7** [comment]
没有消息详情页这一说
![image](https://github.com/masastack/MASA.Stack.Components/assets/93168234/2ce256e0-14bd-46f0-9884-60ef2289098f)
关联这个issue, 之后， 客户端只关联和他有关的消息，如果配置了链接， 就还是直接跳转链接。
