### ISSUE TITLE
Add default page for all item Card list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#435]
所有项目 Card列表增加缺省页

**Comment by MayueCif** [comment]
只针Card 列表增加缺省页，PM 已经添加，参考PM

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Auth/pull/873

**Comment by LazyEar0** [comment]
PM-应用列表
![image](https://user-images.githubusercontent.com/95004531/230343752-ca920c03-0cdd-4396-8d65-2db54648a848.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.PM/pull/341
