### ISSUE TITLE
提供可选项，当导航菜单折叠时，鼠标悬停显示菜单，而不是展开整个NavigationDrawer (moved from Masa Pro issue list)

### ISSUE THREAD

**Issue by wangxuepeng** [masastack/MASA.Stack.Components#438]
Per the suggestions, move the issue from Masa Pro to Masa Stack.
https://github.com/BlazorComponent/MASA.Blazor.Pro/issues/183

### Issue type

sample request

### Description

提供可选项（例如在Settings里添加选项：折叠时菜单样式：浮动 or 展开），实现类似AntDesign Pro那样的导航菜单，当导航菜单折叠时，鼠标悬停在上面，显示浮动的导航菜单，而不是展开整个NavigationDrawer。

这样的界面更紧凑，方便使用。

谢谢。

### Screenshots

![image](https://user-images.githubusercontent.com/4516203/227152975-197d8d78-6b8b-48e8-bb26-33f8be3ca5d0.png)

![image](https://user-images.githubusercontent.com/4516203/227153019-91c9f947-20c7-4e9b-884a-471737ffdd63.png)

![image](https://user-images.githubusercontent.com/4516203/227153199-fc763542-d999-444b-abcf-9ea394552ccf.png)

**Comment by doddgu** [comment]
@wangxuepeng hi，是 [MASA Blazor](https://github.com/BlazorComponent/MASA.Blazor)，不是MASA Stack Component。MASA Stack Component已经有了，但是是跟MASA Stack深度绑定的，其他人用不了
