### ISSUE TITLE
The logout page i18n is not consistent with the global navigation

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#459]
登录/登出页i18n没有和全局导航保持一致。英文状态下，退出登录，登出页仍是中文
![image](https://user-images.githubusercontent.com/95004531/230256851-5c73e731-f275-448e-892f-c445ff52b0af.png)
![image](https://user-images.githubusercontent.com/95004531/230257044-a0282823-ae1a-49c4-b9d3-69dc6b088f92.png)
![image](https://user-images.githubusercontent.com/95004531/230257083-8396c25b-d392-4937-8b49-dc4ae457b505.png)

**Comment by limei7** [comment]
已修复
