### ISSUE TITLE
An account can bind multiple wechat signals

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#461]
一个账号可以绑定多个微信号，扫一扫后，绑定已存在的手机号，即可绑定同一账号
![image](https://user-images.githubusercontent.com/95004531/230259849-ccb2945c-cc70-480e-9cc0-472b8b2267b6.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Auth/pull/1104

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by limei7** [comment]
没看懂这个是什么意思
![image](https://github.com/masastack/MASA.Stack.Components/assets/93168234/c49b20e5-1f9f-4849-b12b-c15fa2cb294f)
这个地方显示3个微信图标是不是也不对

**Comment by limei7** [comment]
微信扫一扫之后， 获取手机验证码之后， 绑定到原有的user下面去， 是没问题的
