### ISSUE TITLE
When changing a user's name, the cancel and save buttons work in reverse.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#462]
修改用户姓名时，取消按钮和保存按钮的功能反了。点取消按钮，保存了输入框的内容，点保存按钮，输入框内容不保存。
![image](https://user-images.githubusercontent.com/95004531/230261420-57a10bfa-37f5-4ee8-8628-3035fa4cc6c1.png)

**Comment by kogel-net** [comment]
#471
