### ISSUE TITLE
Personal information, modify nickname style adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#463]
个人信息，修改昵称样式调整
![image](https://user-images.githubusercontent.com/95004531/230261714-f363249d-a96d-4924-a58d-9aaa58856e85.png)
![image](https://user-images.githubusercontent.com/95004531/230261794-31ab48c6-8ddc-4c2f-9dfc-28b1378fd5fa.png)

**Comment by kogel-net** [comment]
#471
