### ISSUE TITLE
Message center, list search result error.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#470]
消息中心，列表搜索结果错误。
在某一渠道下搜索该渠道的消息（搜索内容+回车键），搜索完成后，切换至另一个渠道，输入上一次输入的搜索内容，不点击回车，列表出现的数据错误

https://user-images.githubusercontent.com/95004531/230283347-7eecd58f-df10-42fa-b2a6-624fe277d7ba.mp4

**Comment by kogel-net** [comment]
#473
