### ISSUE TITLE
The interval between getting SMS CAPTchas should be 1 minute; now it's 5 minutes

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#472]
获取短信验证码间隔应是1分钟，现在是5分钟
![image](https://user-images.githubusercontent.com/95004531/230288708-1c3ccbd4-3deb-40b7-83e6-264e83cd822e.png)

**Comment by MayueCif** [comment]
短信发送时间间隔1分钟，验证码有效期5分钟

**Comment by MapleWithoutWords** [comment]
https://github.com/masastack/MASA.Stack.Components/issues/472
