### ISSUE TITLE
Clicking on the user agreement will trigger the check box to be checked

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#483]
点击用户协议，会触发勾选框的选中状态。用户协议和勾选框的操作应是独立的
![image](https://user-images.githubusercontent.com/95004531/231065265-e974d4db-d900-44cf-8c54-1da693570abc.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Auth/pull/961
