### ISSUE TITLE
个人中心上传头像报错

### ISSUE THREAD

**Issue by MayueCif** [masastack/MASA.Stack.Components#489]
个人中心上传头像目前需要项目里额外引用js，需要调整

**Comment by MayueCif** [comment]
[#993](https://github.com/masastack/MASA.Auth/issues/993)

**Comment by kogel-net** [comment]
https://github.com/masastack/MASA.Alert/pull/268
https://github.com/masastack/MASA.Auth/pull/1005
https://github.com/masastack/MASA.DCC/pull/536
https://github.com/masastack/MASA.MC/pull/434
https://github.com/masastack/MASA.PM/pull/353
https://github.com/masastack/MASA.Scheduler/pull/376
https://github.com/masastack/MASA.TSC/pull/395
