### ISSUE TITLE
Toggle the login/Register tab to trigger the user Agreement window

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#525]
点击用户协议打开用户协议窗口后，关闭用户协议窗口，切换登录/注册tab，会触发打开用户协议窗口操作
![image](https://user-images.githubusercontent.com/95004531/232409471-d8024bcd-b41f-4837-9360-97ec4fab0b65.png)
![image](https://user-images.githubusercontent.com/95004531/232409522-490ab998-f2f2-4b9c-a46f-cb66d82a3396.png)

**Comment by kogel-net** [comment]
https://github.com/masastack/MASA.Auth/pull/1012
