### ISSUE TITLE
No user data can be retrieved after the token expires

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#570]
token 过期后获取不到用户数据
![image](https://user-images.githubusercontent.com/95004531/233915930-66b9d638-18f9-4eda-a4ff-e196cadcc5a4.png)

**Comment by limei7** [comment]
这个BUG是说， 当token过期的情况下， 修改了数据， 这个卡片右下角显示不到是哪个用户修改了数据， 显示不出修改人。

**Comment by limei7** [comment]
1.尝试去auth-客户端-修改alert-staging的令牌配置， 比如修改为120秒
2.去alert-sec-staging查看，2分钟前后， 修改数据， 用户数据还是能取到
3.尝试修改auth-web这个客户端的令牌时间后， 去auth操作一些功能， 没有影响
