### ISSUE TITLE
The custom login, name and title of the seed data do not conform to the specification

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#624]
种子数据的自定义登录，名称和标题不符合规范
![image](https://github.com/masastack/MASA.Stack.Components/assets/95004531/c96fd298-103e-4478-96a3-d7892bcbcbe2)

**Comment by limei7** [comment]
iotdev环境下，复测，当前没有这么多限制， 可以输入纯英文
