### ISSUE TITLE
After switching teams, global navigation goes to other projects and teams change

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#626]
切换团队后，全局导航进入其他项目，团队会发生变化
![image](https://github.com/masastack/MASA.Stack.Components/assets/95004531/d50504ef-5db7-41b9-a496-5d1cc83c4574)
![image](https://github.com/masastack/MASA.Stack.Components/assets/95004531/2075c67a-40bf-4906-a25d-b2809fbeb0e7)

**Comment by limei7** [comment]
iotdev环境测试后，未复现此问题
