### ISSUE TITLE
Personal center . Authorization and authentication. The authentication function of mobile phone number, wechat and email is missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#82]
授权与认证，实名认证，手机号码认证，微信认证，邮箱认证功能缺失；
![image](https://user-images.githubusercontent.com/95004531/177291976-bdd9105f-06a5-487c-b5d7-64bec1365561.png)

**Comment by MayueCif** [comment]
Milestone 1.0
