### ISSUE TITLE
Personal center . Modify password popup style adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Stack.Components#83]
修改密码弹窗样式调整；
实际结果：
![image](https://user-images.githubusercontent.com/95004531/177292603-7dcbdd9d-fa73-470a-be2e-ed87646a27e0.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/177292810-8a1e3a73-efce-4a76-92dd-84f7f4c74f1a.png)

**Comment by capdiem** [comment]
@LazyEar0 无法复现

**Comment by LazyEar0** [comment]
resolved
